"""
SageMath all module type stubs for IDE support
This helps language servers recognize SageMath functions and types
"""

from typing import Any, Optional, Tuple, List, Dict

# Common SageMath functions
def GF(p: int, **kwargs: Any) -> Any: ...
def Qp(p: int, prec: Optional[int] = None, **kwargs: Any) -> Any: ...
def PolynomialRing(base_ring: Any, var: str = 'x', **kwargs: Any) -> Any: ...
def ZZ() -> Any: ...
def Integer(n: Any) -> Any: ...
def xgcd(a: Any, b: Any) -> Tuple[Any, Any, Any]: ...
def lcm(a: Any, b: Any) -> Any: ...
def parent(obj: Any) -> Any: ...
def cmp_to_key(cmp_func: Any) -> Any: ...
def Coefficient(f: Any, n: int) -> Any: ...
def conway_polynomial(p: int, n: int) -> Any: ...
def dilog(x: Any) -> Any: ...

# Common SageMath types
class SageObject:
    def degree(self) -> int: ...
    def is_irreducible(self) -> bool: ...
    def multiplicative_order(self) -> Any: ...
    def valuation(self) -> Any: ...
    def residue(self) -> Any: ...
    def newton_polygon(self) -> Any: ...
    def list(self) -> List[Any]: ...
    def coefficients(self, sparse: bool = False) -> List[Any]: ...
    def constant_coefficient(self) -> Any: ...
    def leading_coefficient(self) -> Any: ...
    def change_ring(self, R: Any) -> Any: ...
    def subs(self, **kwargs: Any) -> Any: ...
    def roots(self, multiplicities: bool = False) -> List[Tuple[Any, int]]: ...
    def factor(self) -> Any: ...
    def is_zero(self) -> bool: ...
    def gen(self) -> Any: ...
    def base_ring(self) -> Any: ...
    def parent(self) -> Any: ...
    def characteristic(self) -> int: ...
    def prime(self) -> int: ...
    def precision(self) -> int: ...
    def uniformizer(self) -> Any: ...
    def ramification_index(self) -> int: ...
    def inertia_degree(self) -> int: ...
    def extension(self, f: Any, names: Optional[Any] = None) -> Any: ...
    def residue_field(self) -> Tuple[Any, Any]: ...
    def automorphisms(self) -> List[Any]: ...
    def cardinality(self) -> int: ...
    def multiplicative_generator(self) -> Any: ...
    def prime_subring(self) -> Any: ...

__all__: list[str]



